### ISSUE TITLE
Add Trees Data Structure

### ISSUE THREAD

**Issue by pratishtha-abrol** [romain325/DataStructuresAndAlgorithms#5]
add the array, and linked list implementations of trees

**Comment by romain325** [comment]
I'll start with binary tree really soon !

**Comment by romain325** [comment]
#11 Linked Issue

**Comment by Richaagrawal314** [comment]
Interested.

**Comment by romain325** [comment]
Of course  go ahead !  
I pushed a C Version and I'll add some function to it 
But you can do it with different techniques/languages !
