### ISSUE TITLE
Add Queue

### ISSUE THREAD

**Issue by romain325** [romain325/DataStructuresAndAlgorithms#6]

**Comment by amitsaini4556** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by romain325** [comment]
I just finished the version if C, wanna do it in another language maybe ?

**Comment by amitsaini4556** [comment]
Cpp ?

**Comment by romain325** [comment]
Perfect ! I've just merged the C Version and I'll assign you on this issue !

**Comment by amitsaini4556** [comment]
Thank you so much.

**Comment by romain325** [comment]
Thanks a lot for your contribution !!
